### ISSUE TITLE
(1) Publication for UA50 UCSC Photo Services

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#101]
Implementation:
- Ned logs into the system, makes a loop to go through all the records, and saves the published flag. 
- Add to the homepage.

**Comment by NedHenry** [comment]
Collection landing page: https://digitalcollections.library.ucsc.edu/collections/jd472x03h

**Comment by kellyChex** [comment]
@chesleyperry Can we close this ticket?

**Comment by NedHenry** [comment]
Not yet. There were some issues with the publication which I haven't yet
confirmed are fixed.

**Comment by NedHenry** [comment]
The background task to publish this large collection completed successfully over the weekend. It appears (to me) that the entire collection is now published. Please let me know if you see any evidence to the contrary. 
The problem before does seem to have to do with the fact that I was doing other ingest work (on the porter college complex objects) which had a problem and messed up the ingest server task queue, interrupting the publication job without properly informing me. 
In the future, when we publish a big collection we should verify that the number of publicly visible works matches the total number of works in the collection (which it now does). 
Unless anyone else sees a problem with this collection, I think this issue is ready to close.

**Comment by NedHenry** [comment]
To confirm - UA50 images are now fully published (which also addresses the broken links which previously showed up in issue #107)
