### ISSUE TITLE
(3) Download Large Option: File + Citation

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#118]
### Descriptive Summary

Offer users the option of downloading both the object file and its citation together in a zip file.

As an end-user, when I click 'Download Large (1000px) + Citation (Zip File)' in the Download modal, I can download both the file and its associated citation in a single package.

### Background 

Originated from Journey Map: Serena from Home
(If a user forgets to copy the citation when they download the desired file, they sometimes cannot remember the origin of the file and then are unable to use it.)

### Acceptance Criteria

This is what done looks like

* [ ] The largest downloadable version of a file and a text file including its citation in all three formats (MLA, APA, and Chicago styles) can be downloaded together in a single zip file

### Mock Ups

<img width="993" alt="Screen Shot 2019-11-27 at 11 56 24 AM" src="https://user-images.githubusercontent.com/9621070/69762135-71388d00-110d-11ea-83dd-b16e971d4eb7.png">

### Related Tickets

We may need to do https://github.com/UCSCLibrary/dams_project_mgmt/issues/115 before this one to prepare for handling citations.

**Comment by kellyChex** [comment]
@JessWaggs This is great start! I think adding the mock ups here make sense. With that, an example of a work with its metadata and how that citation should appear.

**Comment by kellyChex** [comment]
Users should be able to copy all three citation formats listed here? https://github.com/UCSCLibrary/dams_project_mgmt/issues/115

**Comment by JessWaggs** [comment]
![DownloadModal](https://user-images.githubusercontent.com/6412857/69664098-8a253d80-103c-11ea-8bd8-af688e5b390d.png)

**Comment by JessWaggs** [comment]
Allow Download + Citation as single zip file offering both small and large size
Citation would be text file including citation in all 3 styles/formats

**Comment by chesleyperry** [comment]
I've QA'd this and it functions as expected.  But - following up on the Slack conversation from Feb. 27- Mar. 3, we need to change the format of the text file for the citations.  Instead of the metadata properties listed under each citation style.  The text file should have just one listing of the citation information.  See the screenshot from Calisphere.
![Screen Shot 2020-03-17 at 10 02 24 AM](https://user-images.githubusercontent.com/18403313/76882612-24053600-6838-11ea-8030-9e486baee13e.png)
