### ISSUE TITLE
(3) Implement new AV player design   

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#129]
### Acceptance Criteria

This is what done looks like

* [x] Media player block expands the whole width 
* [x] Player to the left of the track list 
* [x] The Part that is playing is highlighted and with an icon
* [x] All other information has moved below the media player block  

### Expected Look 

![Screen Shot 2019-11-20 at 5 47 01 PM](https://user-images.githubusercontent.com/9621070/69293522-f546be00-0bbd-11ea-9f45-a62e852a894e.png)

### Current Look

![Screen Shot 2019-11-20 at 5 46 04 PM](https://user-images.githubusercontent.com/9621070/69293542-07286100-0bbe-11ea-931a-ab0846e62899.png)

### Style Guide: 
Font:
Color:
Icons:

### Engineering Notes 
- Links go to the childs works

**Comment by kellyChex** [comment]
Although this ticket implements a new look for the media player, we may still need to make it functional as noted in #91

**Comment by NedHenry** [comment]
This is now deployed in the sandbox site. You can check out how this looks in different circumstances and make sure it's what you had in mind:
- [A parent work with two child audio works](http://digitalcollections-staging-sandbox.library.ucsc.edu/concern/works/hx11xf24j)
- [The first child audio work](http://digitalcollections-staging-sandbox.library.ucsc.edu/concern/works/hx11xf24j)
- [The second child audio work](http://digitalcollections-staging-sandbox.library.ucsc.edu/records/cc08hf60z)
- [A simple audio work](http://digitalcollections-staging-sandbox.library.ucsc.edu/concern/works/v692t620b?locale=en)

**Comment by NedHenry** [comment]
In reference to Kelly's comment above - I'm not sure that #91 is actually relevant here (though it looks like it would be). That issue is only related to a multi-track playlist implemented in javascript, which we had installed as an extension to our media player (mediaelement.js) to handle complex objects, and then disabled because of #91. This javascript playlist remains broken, but is not required for the changes in this ticket.
This ticket implements a serious of ordinary HTML links that look and act similarly to a playlist, but do not load in javascript. The problematic playlist extension to our media player is never loaded, and we retain full functionality.
It is still a good idea to fix our javascript playlist functionality in the future, because it will offer improvements in performance and the possibility of more user experience improvements and new features in the future. But I do not believe that blocks this ticket's changes from getting deployed.

**Comment by chesleyperry** [comment]
I agree with the points Ned made about the javascript playlist player.  We want to put that aside for now and just display the child works with HTML as Ned has deployed on the sandbox site.  It looks and functions just like we had specified in the mockups. :)
The only issue is the download button, which should only display on image work pages.  I would like to see it on the staging server with some of our real audio content.

**Comment by NedHenry** [comment]
Sounds good, Sue! The removal of the download button is already addressed in the branches related to the download modal functionality, which are now ready for review. 
Since all of this work looks pretty solid, I plan to merge these changes together onto the staging site today so we can test it all with actual content.

**Comment by JessWaggs** [comment]
Sorry - I put this in Slack but I think this ticket is a better place:
I think this looks really good! The only issue I see is that the Items are still listed in the parent record. I think we should hide those in the display, as children will now be accessed through the "Track List"

**Comment by chesleyperry** [comment]
Tested course page: http://digitalcollections-staging.library.ucsc.edu/concern/works/p2676x95k
and lecture page: http://digitalcollections-staging.library.ucsc.edu/concern/works/dr26z052j

Desktop browsers:
Player and display work as expected.  Course page lists the first lecture highlighted, with other lectures listed below it to the right of the player.  The individual lecture pages have the selected lecture highlighted and show the whole list of other lectures to the right of the player.  The other child works do not display below the metadata on the lecture (child) page. 
 The course page DOES list the individual child works below the metadata.  @JessWaggs - from your comment above, I'm assuming you want those hidden on the course (parent) page.

Mobile (iphone) browsers:
Player works as expected but if a user tries to click on another lecture or any metadata link on the page, nothing happens.  I think this is the same problem as the bug reported in #218.

**Comment by NedHenry** [comment]
I agree about the mobile browser issue; we probably just need to implement Ryan's fix that is still in code review now - I thought I'd merged that into staging already, but I guess not. I will make sure that fix is implemented, and if we're still having any related problems we can revisit that issue.

Good to hear that it looks good in the desktop browsers. I will hide the child work list below the metadata on a parent audio work page, so that we can count this as fully complete.

**Comment by JessWaggs** [comment]
Yes, child work list hidden please : ) Thank you!

**Comment by NedHenry** [comment]
Cool. I just deployed an update to the staging site fixing both issues. I had indeed merged in Ryan's changes, but I had made a mistake when I was merging them with another branch that erased some important changes. I found and fixed my error, and now the links seem to work on mobile.
