### ISSUE TITLE
(5) Redesign for single image 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#135]
### Acceptance Criteria

This is what done looks like

* [ ] Default image view is restyled as per mock up
* [ ] Title is restyled as per mock up 
* [ ] Only the area highlighted by the pink box is restyled  

<img width="1016" alt="Screen Shot 2019-11-27 at 6 52 59 AM" src="https://user-images.githubusercontent.com/9621070/69743522-a976a600-10e2-11ea-90f0-0e1dbac8d5dc.png">

Link to Mock Up: https://drive.google.com/drive/u/1/folders/1Ypcd3SdjRgZlzsiRzmwn3Kzc1kSxhK5O

### Current Look: 

<img width="1193" alt="Screen Shot 2019-12-16 at 4 11 34 PM" src="https://user-images.githubusercontent.com/9621070/70953994-42347d80-2020-11ea-8b27-7c594876584d.png">

**Comment by kellyChex** [comment]
I went to http://digitalcollections-staging.library.ucsc.edu/concern/works/k930bx66x?locale=en and see 
![Screen Shot 2020-01-09 at 12 34 15 PM](https://user-images.githubusercontent.com/9621070/72102649-5f393500-32dc-11ea-9277-9bf2509d7f97.png)

@NedHenry Is the image not showing due to the code?

**Comment by rschwab** [comment]
FYI, this started happening on my local dev as well after I pulled the master branch.

**Comment by NedHenry** [comment]
This issue with image display is not caused by the restyling work involved in this ticket, but is a result of unrelated updates to the code that links the DAMS to the image server. The corresponding changes on the image server side were not propagated into our shared docker dev repository and were not reflected in Ryan's dev environment. 
I can open a separate issue to address the update to the dev environment, but I think this one should move forward to QA. It seems to be working as expected on the staging site now.

**Comment by NedHenry** [comment]
An example work can be found here: http://digitalcollections-staging.library.ucsc.edu/concern/works/sn009z462
The link Kelly posted above is now broken, since our staging site now mirrors the content from the production site

**Comment by kellyChex** [comment]
Tested and this looks good!

**Comment by chesleyperry** [comment]
tested.  Looks good but embedding does not seem to work.  Image does not display on a different server.  (Tried library Drupal site and libguide).

**Comment by kellyChex** [comment]
@chesleyperry Did you create a new ticket for the issue you mentioned above? It would be a separate issue.
