### ISSUE TITLE
Fix issues with hitchcock/holmes lectures

### ISSUE THREAD

**Issue by NedHenry** [UCSCLibrary/dams_project_mgmt#143]
### Descriptive Summary
After re-ingesting the hitchcock/holmes lectures, there were a few issues that were resolved related mime types, thumbnail creation, and playlist display. Some of these were resolved in the live site via hotfix while the relevant changes were also simultaneously implemented in development for later deployment through github. However, for some reason, these changes never made it into the master branch of the the webapp repository, and they were overwritten when we next deployed an upgrade to our code. These  issues need to be fixed again in production, and the changes need to be definitely committed to our dams repository.

### Acceptance Criteria

* [x] The hitchcock & holmes lectures do not display playlists
* [x] None of the lectures creates an error page
* [x] All of the lectures have "audio" thumbnails instead of generic work thumbnails
* [x] All of the above changes have been committed to the master branch of our repo and deployed via our capistrano deployment workflow.

**Comment by rmjaffe** [comment]
Looking at these now -- the work page/parent metadata look great.  Seeing the music note thumbnails, but I'm not able to follow the links to the child recordings for either of the Hitchcook recordings. When clicking on the links, I get an error page, "we're sorry, but something went wrong." Holmes is OK.

**Comment by chesleyperry** [comment]
+1 to Rachel's comment with more details.
Done:
The hitchcock & holmes lectures do not display playlists
All of the lectures have "audio" thumbnails instead of generic work thumbnails

Error messages show up for a number of the Hitchcock Child works.  The parent pages display correctly but the many child works have errors for the [1976-77 History of Western Civ ](http://digitalcollections.library.ucsc.edu/concern/works/q237hv503?locale=en)
[Working child](http://digitalcollections.library.ucsc.edu/concern/parent/q237hv503/works/wh246v350)
[Child with error](http://digitalcollections.library.ucsc.edu/concern/parent/q237hv503/works/cr56n3225)

Error message: "We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

All of the child works for the [70-71 History of Western Civ](http://digitalcollections.library.ucsc.edu/concern/works/m613n0790?locale=en) have errors.

**Comment by kellyChex** [comment]
Moving back To Do with Needs Rework label

**Comment by NedHenry** [comment]
I found and fixed the problem on the production site. The system was not recognizing the audio mime types defined in my samvera_hls gem for some reason. I explicitly defined them in our file_sets.rb file, fixing the problem. I am also adding a gentle failsafe if this problem happens again, so that the rest of the page will display correctly and no error will display.

**Comment by kellyChex** [comment]
@chesleyperry Do you see missing thumbnails here? http://digitalcollections.library.ucsc.edu/concern/works/m613n0790?locale=en

**Comment by NedHenry** [comment]
I am currently not seeing any issues with broken thumbnails for these images. Let me know if anyone else sees anything different.

**Comment by rmjaffe** [comment]
They look good to me.

**Comment by chesleyperry** [comment]
I think the thumbnail issue was fixed in the last round.  I'm not seeing any broken thumbnails or images.  
All errors on the item play pages seem to be fixed too.  Yay!  Thanks Ned!

**Comment by kellyChex** [comment]
Ok, moved to done!
