### ISSUE TITLE
(1) Prepare ingest spreadsheet for combined campus history collections

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#152]
### Descriptive Summary

Restructure spreadsheet to include collection of collections and collection-level metadata rows.

### Acceptance Criteria

This is what done looks like

* [x] RJ restructures spreadsheet
* [x] Spreadsheet handed off to NH for feedback
* [x] Spreadsheet either OK or handed back to RJ for revision

**Comment by rmjaffe** [comment]
@NedHenry I've finished work on the spreadsheet.  The latest and greatest version can be found in the dams_ingest folder (smb://artifacts.library.ucsc.edu/dams_ingest/Combined_Campus_History/CampusHistoryCollections_Ingest_20191218.xlsx).  If you would, please take a look and share any feedback.  There are six complex objects in this set; they are coded neon yellow in the first column.

**Comment by NedHenry** [comment]
This looks awesome, Rachel. It looks like exactly what we talked about. Looking over it, I don't see any issues with the spreadsheet. 

As a note on the ingest specification, it does seem unwieldy to define all the parent relationships based on row number. Add a row in the middle of the spreadsheet now takes a lot of care and attention. For future spreadsheets, we should start thinking about other ways to do it.
At this point, I see two solutions to this that would be totally straightforward to implement. 
First, you can include an extra column that does not correspond to any metadata field (called, for example "spreadsheet identifier"). The ingest software can easily be configured not to consider this field as a metadata field (ignoring a field is already one of the options for an ingest in my bulk ops software. These options are currently specified in the first line of the spreadsheet but will in the future be controlled through the browser interface). You could then assign whatever unique value you want in this column (for example, assign the collection a spreadsheet identifier of "MS90"). You could then reference this value instead of the row number when specifying a parent work (e.g. "spreadsheet identifier:MS90" instead of "row:34").
Second, if the parent row has any unique metadata not shared or inherited by its children (e.g. an accessionNumber) you can specify the parent row based on that metadata field directly (e.g. "accessionNumber:MS0020_rmb_9044_12c" instead of "row:5"). This is probably the easiest method when the parent does have its own unique metadata. 

Both of these features are already nearly fully implemented, but are not currently in use or covered by any tests. I think should only take a few points to get them both working consistently, and a few more to document the features. We should probably do this work before too many more ingests, at least before it becomes a pain to manage big ingest spreadsheet that reference row numbers a lot (Rachel, please let us know when that is).

If this all makes sense to you all, I can create a ticket for implementing expanded object references in ingest spreadsheets.

**Comment by rmjaffe** [comment]
Thanks, Ned!  

Yes, using the row numbers is not always ideal.  Either of the solutions you've described would be helpful especially the former.  If I recall, we'd kind of talk about that with the dummy identifier thing a couple years ago.  

If it makes sense time- and effort-wise, I could see we could testing one or both of these solutions with the forthcoming Cabrillo Music Festival ingest.  Or instead we could link the object reference enhancement work to the UA 50 image grouping/reingest or the aerial photos.  The other collections queued up for ingest, sparing Lick, are legacy simple object stuff.
