### ISSUE TITLE
(2) Mock-up facet display in desktop and mobile

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#200]
### Descriptive Summary

Mock-up facet display, including interactions for selecting and deselecting facets, in both desktop and mobile

### Acceptance Criteria

This is what done looks like

* [x] Mock-up for desktop
* [x] Mock-up for mobile

**Comment by JessWaggs** [comment]
Desktop showing facets in their default state and facets where one group is open with one selected:

![Desktop Facets Closed](https://user-images.githubusercontent.com/6412857/79818495-d438f380-833c-11ea-9599-32fe259a5189.png)

![Desktop Facet Open](https://user-images.githubusercontent.com/6412857/79818503-d733e400-833c-11ea-96fe-38692e7772e6.png)

**Comment by JessWaggs** [comment]
Mobile showing default state and one group open with one facet selected:

![Mobile Facets Closed](https://user-images.githubusercontent.com/6412857/79818629-1a8e5280-833d-11ea-9e47-9899ac67e0a3.png)

![Mobile Facet Open](https://user-images.githubusercontent.com/6412857/79818635-1d894300-833d-11ea-8c9b-66979ab86b47.png)

@chesleyperry What do you think about the blue background with white facet labels for the mobile?

**Comment by rmjaffe** [comment]
@JessWaggs "I'm assuming we can't/won't match collections using facets? So this mock up shows removal of the Matching Collections box once a facet is invoked."  This would be my assumption as well.

Unrelated question:  If, on the initial results screen after having searched "Protest," the user clicked on one of the matching collections.  Would they be delivered to the collection landing page (#153 Mock up for collection landing page)?  Would the scope (not sure how to describe this) automatically be limited to "Protest" or would they need to enter that search again on the collection landing page in order to limit results to the protest images within that matching collection?

**Comment by JessWaggs** [comment]
@rmjaffe Good question! I imagine it leading the user to the collection landing page and not pushing the query through. So the user would need to re-run the search within the collection.

My hope would be that we would set this up so that only highly relevant collections would be pulled, and not just any collection that included an item that keyword matched the search query.
