### ISSUE TITLE
(2) Research on Collections of collections

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#234]
### Descriptive Summary

As a metadata person, I want to be able to record collection of collection level metadata on the ingest spreadsheet.

Consider using the User Story format:

As a archivist, I would like to group related collections together in ur-collections.

### Background 

Additional information about the reason for the feature or story. 

### Acceptance Criteria

* [x] A better sense of whether this strategy is viable
* [x] A better sense of how much work would be involved in implementing it.

**Comment by NedHenry** [comment]
I tested out on my development instance the creation and saving of nested collections. Collections of collections offer no complications in the preservation or indexing steps. This means that Fedora and Solr can successfully store nested collections without any problem, and I don't think that I need to make any changes to the ingest code to accommodate collections of collections.
On an ingest spreadsheet, it should be possible to create collections the same way we create works, with one row corresponding to each collection. To specify which rows are works and which are collections, there should be a column labelled "type" or "work type", which should be set to "collection". The default value of this column is "work", so all rows will correspond to works unless otherwise specified. In either work or collection rows, the "parent" column is used to specify other works or collections that this work belongs to. I believe that all of this has already be implemented, and just needs to be tested to make sure it works as expected with actual collections and metadata.

The display of collections of collections will take a little development. I do not expect any of this to be particularly time consuming. 
- include the "About Collection" box on collection landing pages when the collection belongs to another collection
- include collections of collections in breadcrumbs where appropriate
- make sure metadata inheritance works as desired for collections of collections

**Comment by rmjaffe** [comment]
@NedHenry Thank you for looking into this.  I'm glad it seems straightforward and all makes sense to me.  Once Sue and I have the combined campus history spreadsheet together, I'll update the formatting to indicate that the archival collections are the children of the parent "campus history" collection. 

@JessWaggs Will we want to create tickets for the display changes that Ned has noted?
