### ISSUE TITLE
(3) Testing and documentation standards for new development

### ISSUE THREAD

**Issue by crisr15** [UCSCLibrary/dams_project_mgmt#256]
An agreement on the level of testing that should be added in with any new feature/development effort.  Additionally, a discussion around documentation standards and best practices.

Begin to map out timeline and strategy for each of these pieces.

### Related Work
Epic waiting to be populated:  Increase Test Coverage #76 
Epic waiting to be populated: Code Documentation & Style Standards #75

**Comment by rmjaffe** [comment]
@crisr15 Am I correct in thinking that this might be the beginnings of an epic card?

**Comment by crisr15** [comment]
@rmjaffe This is something that Ned wanted to meet with Rob about, so we would want to check in with Ned about if he wants to make an epic around it or not.  This card was a placeholder to make sure it did not get lost or forgotten before more devs joined the team.

**Comment by NedHenry** [comment]
In our initial meeting with Rob, he suggested that we: 
- write unit tests covering all of our code that has significant logic
- write acceptance tests covering the most important user stories

The unit tests are very relevant to Ned's work, and should be incorporated into his workflow. All new code he writes for the project should be covered by unit tests. I think that these unit tests are only relevant to Ruby methods in our context, and not so much for HTML/CSS/JS. That means that Ryan doesn't need to worry about unit testing unless/until he starts writing Ruby methods. We can double check with Rob about that next meeting.

The acceptance tests cover important user experiences that we want to make sure are working. We should add new acceptance tests whenever we add a feature that we will consider important. These tests can also be added whenever Ryan feels that his front-end work would benefit from test coverage, since acceptance tests can cover the interaction of front-end components like HTML, CSS, JS, etc.

We also discussed "smoke tests" which can run after deployment, and how it probably makes sense to do only a very simple version of this.

**Comment by NedHenry** [comment]
As far as becoming an epic, I think the existing epic about "improving test coverage" could be expanded to include this topic. One "Automated Test Coverage" epic is probably enough. We can create several tickets to contribute to this epic.
