### ISSUE TITLE
(3) Fix display order for tracks in CMF first ingest and collection

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/dams_project_mgmt#283]
### Descriptive Summary

Before we can merge the two Cabrillo Music Festival collections, we need to check and fix the display order for the child works for the concerts.

### Background 
See examples: http://digitalcollections.library.ucsc.edu/concern/works/rr1720558?locale=en
and
http://digitalcollections.library.ucsc.edu/concern/works/2f75rb35b?locale=en

### Acceptance Criteria

This is what done looks like

* [ ] Child works display in numerical order

### Related Work 

After this collection is fixed, it will be merged with the other Cabrillo collection (#274)

**Comment by NedHenry** [comment]
It turned out that the correct order was actually saved in Fedora already, but Solr had indexed the wrong order. This was caused by an indexing bug which I since fixed. All that was needed to resolve this issue was to save and re-index the works in this collection. The order is now correct for every example I've checked.
