### ISSUE TITLE
(1) Add metadataSource property to metadata schema

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#342]
### Descriptive Summary

Property to be added to metadata schema/config file to accommodate collection-level metadata source notes, i.e. where the descriptive information originated, who contributed to it, what issues may exist within it.

### Acceptance Criteria

This is what done looks like:

* [x] metadataSource added to schema
* [x] Discuss/create related tickets:  how/where will this information display on the collection landing pages, etc.

### Related Work 

#285 Determine best strategy for adding collection level info to older collections
#341 Gather collection-level metadata source/sensitivity notes for already published collections

**Comment by NedHenry** [comment]
I am adding this metadata field now. 
For now, I have set it up so that this field is stored in Fedora but not displayed on the front end. The value of this field will be included in full-text searches of the site, but I have not included an option to search records specifically by values in this field, nor is this field a facet. I have created a local stand-in predicate for this field, which means the field won't map to any external authority's predicate that might have a universal semantic value. I have set it so that members of a collection do not inherit this value from the collection. Let me know if you would like to change any of this. Below is the entry I am adding to the config file corresponding to this new field:

  metadataSource:
    definition: Notes about the source of metadata i.e. where the descriptive information originated, who contributed to it, what issues may exist within it.
    label: Metadata Source
    hidden: true
    predicate: local:metadataSource
    display_group: admin_only
    inheritable: false

**Comment by rmjaffe** [comment]
Thanks, @NedHenry.  This is perfect; that said, I want to check with @JessWaggs:  Do we want to display Metadata Source statements within the description box (#222) on the collection landing pages?  If so, as part of that work, we'll need to unhide this property.

**Comment by rmjaffe** [comment]
Created work ticket #384.
