### ISSUE TITLE
(3) Design any necessary front-end for nested collection display

### ISSUE THREAD

**Issue by NedHenry** [UCSCLibrary/dams_project_mgmt#348]
### Descriptive Summary

There are some design decisions that need to be made about displaying collection-of-collection relationships before we can start work on implementing this functionality.
Some questions to answer:
- On a work page, we have created a box displaying information about the collection that the work belongs to. Do we need to display any information on a work page about the parent collection that contains the collection that contains the work?
- On a collection landing page, do we want a box displaying information about the parent collection that the collection belongs to? If so, should this box look any different from the "About Collection" box on a work's page?
- On a parent collection landing page, do the child collections need to be displayed any differently than child works on a normal collection landing page?
- Should parent collections, child collections, and works all be jumbled together in search results? Should search results only search within some of these categories in some contexts?

### Background 

We are in the process of implementing nested collection functionality (collections of collections). The ingest and indexing of nested collections is essentially built in already, but we will probably have a little front-end development work to do to make these relationships display the way we want. This issue is about determining the scope and nature of that front-end development work. 

### Acceptance Criteria

* [ ] We have made and documented all easily foreseeable decisions about how to display nested collection relationships on our site
* [ ] We have mock-ups of any new display elements we want to include

### Related Work 

#347 #350

**Comment by JessWaggs** [comment]
Related Tickets:
#153 Mock Up for Collection Group page (and Collection Landing page)
#231 Creating Collection Group page based on mock up

**Comment by JessWaggs** [comment]
Some initial thoughts based on my thinking when designing the mock ups:

1) I don't feel the need to include parent collection information in the About the Collection box because I foresee a time where a collection might have multiple parents and that would become too confusing to display graphically. 
2) This might be nice to include on the collection landing page, it could be done as a list (eg. "This collection is included in:") so the multiple parent issue wouldn't be a problem. Another possibility would be listing "Related Collections" (siblings) rather than parents. Could do with thinking though a bit more.
3) We do want a very different look/feel for displaying child collections on a parent collection page. See #153 and #231 
4) Collections should be placed in the "Matching Collections" box on the search results page rather than jumbled in with works results (see #199 and #224). I hadn't thought about whether matching collections should include both child collections and parent collections. I guess why not both?
