### ISSUE TITLE
Add a sort property to the metadata config file

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#366]
### Descriptive Summary

In keeping with our UI design mockups, we would like to be able to select how works will be sorted (i.e. the order in which they are displayed) on our collection landing pages.  We would like to build this functionality into our metadata configuration file.

We would like to be able to sort works by either title or dateCreated.

### Background 

A-Z sorting was originally added as an acceptance criterion on our collection landing page design tickets.  Determining the sort was removed from those tickets and this new work ticket was created.

### Acceptance Criteria

This is what done looks like

* [ ] Sorting mechanism added to metadata configuration file
* [ ] We are able to display works on the collection landing pages in A-Z or chronological order

### Related Work 

#176 Apply collection landing page design desktop
#276 Apply collection landing page design mobile
#275 Collection landing page for CMF
#363 Collection landing page for SC Co. History

**Comment by rmjaffe** [comment]
@NedHenry @rschwab I wrote this up as best as I could based on our discussion during the planning meeting.  Please feel free to add/revise.

**Comment by rschwab** [comment]
Noting here Kate's request for Created Date sorting.

**Comment by NedHenry** [comment]
This work was pretty much all done while working on UCSCLibrary/dams_project_mgmt#324. Adding the sort property to the config file turned out to be the easiest way to do the work in that issue. 
That issue is still in progress because it requires a re-index of the whole collection. Once that work is completed and tested, all we need for this issue is to document the config file better (which is mostly UCSCLibrary/dams_project_mgmt#229).

**Comment by rmjaffe** [comment]
@NedHenry -- Thanks for the update.  Based on what you've shared, I'll close this ticket out move it to done.

**Comment by rmjaffe** [comment]
Also unblocked UCSCLibrary/dams_project_mgmt#277 and UCSCLibrary/ucsc-library-digital-collections#375.
