### ISSUE TITLE
(3) Discuss Hide links to child URLs & forward requests to those URLS 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#38]
### Descriptive Summary

-  Hide links to child URLs & forward requests to those URLS
We decided that some child works will not have their own display pages, but will only be displayed as part of the parent work.
These child work urls will point to the parent work page with the child work highlighted.

-  Check and fix hidden work indexing
When a child work does not display on its own page but has unique metadata, we should ensure that this metadata is indexed (or not) the way we want. If you search for metadata of a hidden child work (e.g. a child work called "table of contents" that does not display alone) should you get the parent work (e.g. books that have tables of contents) or nothing? I developed this flexibly but configured it haphazardly, so I need to write down exactly how it works now so I can ask exactly how we want it to work. Reconfiguration of the details should be easy once the software works.

### Additional Notes 

We need to discuss this ask in more detail as a part of the next sprint. 

The UV appears to be unstable. Does it make sense to hide at this point.

**Comment by NedHenry** [comment]
Can I ask what the nature of the observed instability with the Universal Viewer is? I'd love to keep tabs on that!

**Comment by kellyChex** [comment]
@NedHenry Performance issues captured in https://github.com/UCSCLibrary/dams_project_mgmt/issues/36 

I've got a few other concerns:
- This seems like a big customization move. How will this effect future Hyrax upgrades? 
- Will it be easy to view the metadata in the UV? How much effort is this? etc.
- How much is the UV at risk for going down. For instance, it's currently showing with an error in Nurax:

![Screen Shot 2019-10-09 at 9 16 55 AM](https://user-images.githubusercontent.com/9621070/66499957-9ac22a00-ea75-11e9-97e3-fff5fb75c7d0.png)

**Comment by NedHenry** [comment]
Oh I understand now! Those do seem like good things to discuss for our future plans. Thanks for clarifying.
I misread that at first, and thought someone had observed problems with UCSC's current production implementation of UV, which has been working fine to my knowledge (although it has been a bit slow to load complex objects, at least on the staging site over VPN).

**Comment by NedHenry** [comment]
It's worth noting that this issue comes from a to-do list item that I wrote while thinking about works like the Porter College Scrapbook (an album of pages, where each page has minimal metadata). We decided to structure works like that in a different and better way (details below), so the work in this ticket is no longer necessary for anything immediate. This customization may not be necessary at all, but is worth discussing. 
For the porter college collection, I was (foolishly) trying to import each page of the scrapbook as a separate work with a single fileset, instead of having a single work for the scrapbook with multiple attached filesets for each page. That would have required hiding the child works from search results and links, because it doesn't make sense to have each scrapbook page show up separately when they are easily visible together. It also would have required some customization of Universal Viewer, especially if we wanted to be able to display metadata associated with the individual pages. 
Yesterday morning Rachel asked if this strategy was really necessary, and I realized that it wasn't. I re-imported that scrapbook as a single work with each page as a fileset (with no works associated with individual pages). I don't think any further customization of UV is necessary for this work. 
[Here is the scrapbook in staging with a work (and fileset) associated with each page](http://digitalcollections-staging.library.ucsc.edu/concern/works/5712m7377?universal_viewer=true&locale=en).
[Here is the scrapbook in staging with just a fileset for each page](http://digitalcollections-staging.library.ucsc.edu/concern/works/pv63g0855?universal_viewer=true&locale=en)
We may still want some of these features in the future for other works/collections, and some of the thought process may still apply to A/V works (although they will not be using the UV).

**Comment by kellyChex** [comment]
We've determined the following actions will be done after speaking with other Samvera developers:
1. Make the filesets into child Works as we want the files to be searchable and with their own metadata.  
2. Attempt to display the child work metadata display in the UV (if not, will display child work metadata somewhere on the page).
3. Include ability to page through child works without having to reload the page.  
4. Create mockups to clean up style once we've proved we can do 2 & 3. 
5. Defer decision to hide links once 2 & 3 are actioned.

@NedHenry @rmjaffe @chesleyperry @JessWaggs please review this action plan. Once officially approved I will move this ticket to Done.

**Comment by rmjaffe** [comment]
@kellyChex Yes, this is my recollection of our conversations.

**Comment by kellyChex** [comment]
#92 #93 #94 are stories for 1, 2, and 3 listed above.
