### ISSUE TITLE
(1) Linked text "next" does not work in the pager of browse pages or search results

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/dams_project_mgmt#404]
### Descriptive Summary

The pager that displays at the bottom of public pages with more 10 results has the word "next" for moving to the next page of results.  This doesn't work right now.  Clicking on a page number, such as 2 or 3 does work.  "Previous" also works. 
Screenshot:
![Screen Shot 2020-11-12 at 1 43 01 PM](https://user-images.githubusercontent.com/18403313/99000421-1a7abd80-24ee-11eb-8c90-f98dece29c65.png)

Consider using the User Story format:

As a public user, I want to click on the "next" pager and have the site advance to the next set of results. 

### Background 

I checked the staging and production sites in Mac Chrome, Mac Firefox, and iOS Safari and they all fail.

### Acceptance Criteria

This is what done looks like

* [ ] "Next" links function as expected in mobile versions of the site
* [ ] "Next" links function as expected in desktop versions of the site

**Comment by NedHenry** [comment]
I added a fix that is a bit ugly, but it should work. I'm pretty sure this happened because Blacklight uses glyphicon chevron symbols for the previous and next links, and Bootstrap reserves those for showing and hiding content. I think the bootstrap javascript messed up the links on the Blacklight pagination.
Instead of trying to override all the blacklight view scripts, I just added a little javascript to swap the glyphicons in the pagination code.
