### ISSUE TITLE
(2) Lick Work Titles with accented characters not diplaying 

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/dams_project_mgmt#418]
### Descriptive Summary

A short description of the feature, including wireframes, screenshots, or videos if available.

https://digitalcollections.library.ucsc.edu/concern/works/vh53wz85d?locale=en:  Accented character in title diplaying as _.  Hugo Gyldén displaying as Hugo Gyld__n

https://digitalcollections.library.ucsc.edu/concern/works/j9602402h?locale=en:  Rudolf Lehmann-Filhés displaying as Rudolf Lehmann-Filh__s |  

### Acceptance Criteria

This is what done looks like

* [x] Accented characters display properly.

### Related Work 

#390

**Comment by rmjaffe** [comment]
@NedHenry Let me know if there's anything I can do on my end in terms of helping resolve this or preventing it from happening in future ingests.

**Comment by NedHenry** [comment]
I resolved this for the Lick works, but have not yet gone back and ensured that it will not happen again. That requires revisiting the Github API, which changes periodically. 
It should be a straightforward code change to resolve this for the immediately future. It will be more challenging, but still worthwhile, to write a test to automatically check that this functionality is working. This test is especially complex because it interacts with an outside API and publicly visible data, but it is also especially useful because this is a feature that has broken unexpectedly more than once.

@rmjaffe No need to do anything different on the spreadsheets for this, the spreadsheet data is not a problem. Is it purely a character encoding issue when interpreting the spreadsheet in Ruby after downloading it from Github (UTF vs ASCII).
