### ISSUE TITLE
(1) View all collections button doesn't work if someone uses the "browse collections link"

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/dams_project_mgmt#423]
### Descriptive Summary

Reported by a user:  "I'm using Chrome, and I have found on four occasions (twice yesterday and twice today) that, upon first arriving on the homepage, the "View All Collections" button doesn't open up and display all the other collection boxes as it should unless I immediately refresh the homepage and then try again. Once I do that it seems to function as I imagine it should."

From Sue:  I haven't been able to replicate this exactly, but I did find that if I click on the "browse collections"link in the header, the "view all collections" link doesn't work, as described above.

### Acceptance Criteria

This is what done looks like

* [ ] The view all collections link works all the time

**Comment by rschwab** [comment]
This was caused by a conflict with the javascript I wrote and Turbolinks, which is a part of rails that improves page loads. I had to replace a function in several javascript files, so testing should ideally be done on:
- The view all collections button
- The citation copy button
- The embed widget functionality
- The show/hide facets button
- The title tooltips loading on search results pages

**Comment by chesleyperry** [comment]
Chrome/Mac:
The view all collections button - works!
Embed image works!
Show/hide facets works!
Title tooltips on search results pages - works
