### ISSUE TITLE
(5) Ingest UA36 Lick Collection - Simple Objects

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#56]
### Descriptive Summary

Large image collection which contains one series of simple objects as well as a series of complex objects (albums and front/backs). This ticket focuses on the ingest of the simple objects.

### Background 

This is a legacy collection currently up in CONTENTdm.

### Acceptance Criteria

This is what done looks like:

* [ ] Collection has been successfully ingested
* [ ] Images display properly
* [ ] Metadata displays properly
* [ ] Collection has been published and is available to users on DAMS homepage

### Related Work 

Lick pre-/post-ingest card #169

**Comment by NedHenry** [comment]
Current Status:
The ingest is stalled because of file processing issue introduced by the Hyrax upgrade (#353). The upgrade required a new version of Ruby that [has known problems transferring files from one NFS server to another](https://bugs.ruby-lang.org/issues/16965) (we transfer files from dams_ingest to dams_derivatives during the ingest process). 
There are several possible workarounds, including downgrading Ruby to an intermediate version or patching the file transfer code to handle the error and fall back to a working transfer method. I am now researching which option will be fastest and most reliable, and then to implement that option.  
Done:
- Reviewed and uploaded the ingest spreadsheet
- Ran verification scripts to ensure the spreadsheet is properly formatted and the files are all there
- Started ingesting the first 200 images
- Verified that the metadata is ingesting properly for these images (despite file ingest errors).

**Comment by rmjaffe** [comment]
While very casually perusing the collection, I noticed one image that appears not to have loaded successfully: https://digitalcollections.library.ucsc.edu/records/n009w5347

**Comment by chesleyperry** [comment]
I'm finding a few different issues so creating a separate QA and bug ticket for Lick
